<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules.User.Application\Modules.User.Application.csproj" />
    <ProjectReference Include="..\Modules.User.Infrastructure\Modules.User.Infrastructure.csproj" />
  </ItemGroup>

</Project>
