@Web.Api_HostAddress = http://localhost:5229

GET {{Web.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Web.Api_HostAddress}}/users
Content-Type: application/json

{
  "username": "alice"
}

###

@UserId = 00000000-0000-0000-0000-000000000000

GET {{Web.Api_HostAddress}}/users/{{UserId}}
Accept: application/json

###
